### ISSUE TITLE
steam默认版本为1.2.15，且无法更新

### ISSUE THREAD

**Issue by Freesheep5299** [Vetoyi/CN_Patch.College_Kings#1]

**Comment by ghost** [comment]
确实版本升级后无效了

**Comment by Vetoyi** [comment]
作者自2月以来进行了多次更新，导致原0.04补丁不再适配当前游戏版本，最近一次更新则是4天前的1.2.16(btw我很高兴作者终于在这次更新中封包了游戏文件，根目录看着清爽多了，虽然解包后的文件数量依旧堆积如山)。

说回汉化补丁，我目前依旧暂无更新打算，一方面同先前一样是出于作者可能还会更新导致又得重弄的考量，另一方面是目前暂时不想再处理补丁相关事宜，所以目前依旧只能是无法汉化游玩状态。

**Comment by ZhaoRongTian1** [comment]
作者大大打算什么时候更新呢

**Comment by Vetoyi** [comment]
我暂时也说不准，毕竟鸽是常态，目前更多还是在忙现实事情，光就补丁而言也还有好几个想再更新下，但动力和时间却不如以往了，之后再看看吧。
@ZhaoRongTian1

**Comment by Sco-ohhG** [comment]
> 我暂时也说不准，毕竟鸽是常态，目前更多还是在忙现实事情，光就补丁而言也还有好几个想再更新下，但动力和时间却不如以往了，之后再看看吧。 @ZhaoRongTian1

期待更新

**Comment by nature1874** [comment]
解压密码是多少啊

**Comment by Vetoyi** [comment]
2024.03.01，CK汉化补丁已更新0.05版，适配至游戏版本1.4.6。
