### ISSUE TITLE
安装完成后会跳出这个错误，我是第一次下载写这个游戏，所以应该没有另外的汉化包

### ISSUE THREAD

**Issue by YG-netect** [Vetoyi/CN_Patch.College_Kings#2]
I'm sorry, but an uncaught exception occurred.

While loading the script.
ScriptError: Name ('game/phone/phone.rpy', 1706388209, 377) is defined twice, at phone/Phone.rpyc:1 and game/phone/phone.rpyc:1.

**Comment by Vetoyi** [comment]
CK的汉化补丁很久没更新了，导致其适配的游戏版本落后于当前Steam最新版本，所以会出现N多报错、汉化失效的问题，也就是说目前用不了汉化了。

需要中文的话只能等更新新的汉化补丁解决，目前仍未着手，有空的话我可能会在春节期间更新。

**Comment by YG-netect** [comment]
感谢回答，不过最近横空出世的翻译软件RenpyThief可以很好解决

**Comment by Vetoyi** [comment]
2024.03.01，CK汉化补丁已更新0.05版，适配至游戏版本1.4.6。

**Comment by checkMeAlr** [comment]
> 感谢回答，不过最近横空出世的翻译软件RenpyThief可以很好解决

确实是 横空出世, 因为做包装 还花钱做宣发了..
所以还是不建议给这款软件付费, 基本上全部功能都是拿的 开源/ 没保护的免费项目 实现的.
