### ISSUE TITLE
college kings汉化出错

### ISSUE THREAD

**Issue by dndnk** [Vetoyi/CN_Patch.College_Kings#3]
<img width="1280" alt="屏幕截图 2024-08-28 112606" src="https://github.com/user-attachments/assets/79df9b09-eb19-4d34-bc3b-41c0d93c537c">
我是按照汉化步骤一步一步做的，然后开始新游戏依然没有汉化，打开原来的原版英文存档，就出现上述图片错误，游戏是卸掉重新下的，不知道出了啥问题

**Comment by Vetoyi** [comment]
存档问题：与汉化无关，你应该会发现就算是纯原版无汉化，载入旧存档依旧会报错，这是开发组持续更新游戏导致的问题，只能重新玩或者导入新版本的存档。

汉化问题：0.06版汉化补丁更新后至今游戏版本依旧停留在1.4.18，再经实测汉化补丁文件无误。如确定已完全按照步骤解压，请尝试下在游戏设置--语言，重新启用下简体中文（选English再选回中文）。

**Comment by dndnk** [comment]
多谢，已经好了
